package com.example.engine

data class LocalizedStrings(
    val appTitle: String,
    val tabYesNo: String,
    val tabChoice: String,
    val tabShop: String,
    val tabHistory: String,
    val askQuestionHint: String,
    val speakQuestion: String,
    val divineButton: String,
    val diviningPrompt: String,
    val touchToCommune: String,
    val voiceListening: String,
    val needOptionsHint: String,
    val addOption: String,
    val chooseForMeButton: String,
    val presetsTitle: String,
    val presetFood: String,
    val presetWeekend: String,
    val presetFocus: String,
    val presetYesNoQuestions: List<String>,
    val alignmentLabel: String,
    val stardustLabel: String,
    val dailyMeditation: String,
    val meditateBonusReceived: String,
    val premiumBannerTitle: String,
    val premiumBannerSub: String,
    val upgradeToPremium: String,
    val premiumPerksTitle: String,
    val perkNoAds: String,
    val perkOffline: String,
    val perkExclusiveSkin: String,
    val perk2xStardust: String,
    val perkAllStyles: String,
    val priceTwoDollars: String,
    val buyPremiumAction: String,
    val restorePurchases: String,
    val premiumUnlockedTitle: String,
    val offlineModeTitle: String,
    val offlineModeDesc: String,
    val offlineLockedWarning: String,
    val offlineActiveSuccess: String,
    val simulatedOfflineToggle: String,
    val simulatedOfflineActive: String,
    val simulatedOnlineActive: String,
    val historyEmpty: String,
    val historySearchHint: String,
    val filterAll: String,
    val filterYesNo: String,
    val filterChoice: String,
    val filterFavorites: String,
    val clearHistory: String,
    val clearHistoryConfirm: String,
    val askAgain: String,
    val shopTabSkins: String,
    val shopTabAnimations: String,
    val shopTabStyles: String,
    val equipAction: String,
    val equippedLabel: String,
    val unlockFor: String,
    val needMoreStardust: String,
    val adInterruptionTitle: String,
    val adInterruptionDesc: String,
    val adSkipIn: String,
    val adDismiss: String,
    val adUpgradeCTA: String,
    val languageTitle: String,
    val voiceErrorPermission: String,
    val voiceErrorNoSpeech: String
)

object LocalizationManager {
    fun getStrings(langCode: String): LocalizedStrings {
        return when (langCode) {
            "es" -> SPANISH
            "fr" -> FRENCH
            "de" -> GERMAN
            "ja" -> JAPANESE
            "zh" -> CHINESE
            "pt" -> PORTUGUESE
            "it" -> ITALIAN
            else -> ENGLISH
        }
    }

    private val ENGLISH = LocalizedStrings(
        appTitle = "Crystal Oracle",
        tabYesNo = "Yes / No",
        tabChoice = "Decide",
        tabShop = "Sanctum",
        tabHistory = "Chronicles",
        askQuestionHint = "Ask your question to the ethereal sphere...",
        speakQuestion = "Speak Question",
        divineButton = "Gaze Into Crystal",
        diviningPrompt = "Communing with the cosmos...",
        touchToCommune = "Rub or tap the crystal orb to focus arcane energy",
        voiceListening = "Listening... Speak your query clearly",
        needOptionsHint = "Enter at least 2 options for the oracle to choose",
        addOption = "Add Choice",
        chooseForMeButton = "Divine My Choice",
        presetsTitle = "Mystic Templates",
        presetFood = "What to Eat?",
        presetWeekend = "Weekend Destiny",
        presetFocus = "Daily Focus",
        presetYesNoQuestions = listOf(
            "Will my current venture flourish?",
            "Is true romance approaching my path?",
            "Should I make that bold purchase today?",
            "Is it time to begin a fresh chapter?",
            "Will good news arrive before sundown?"
        ),
        alignmentLabel = "Cosmic Harmony",
        stardustLabel = "Stardust",
        dailyMeditation = "Daily Crystal Attunement",
        meditateBonusReceived = "+100 Stardust absorbed from cosmic leylines!",
        premiumBannerTitle = "Ascend to Archmage Premium",
        premiumBannerSub = "Permanently eliminate ads, unlock offline channeling, and claim the celestial Archmage skin.",
        upgradeToPremium = "Ascend for $2.00",
        premiumPerksTitle = "Archmage Privileges",
        perkNoAds = "Zero advertisements forever",
        perkOffline = "Offline Divination anytime, anywhere (No internet needed)",
        perkExclusiveSkin = "Exclusive 'Archmage Eternity' Golden Orb Skin",
        perk2xStardust = "2x Stardust gained on every divination",
        perkAllStyles = "All Mystic Fortune Styles instantly unlocked",
        priceTwoDollars = "$2.00 One-Time Lifetime",
        buyPremiumAction = "Purchase Access • $2.00",
        restorePurchases = "Restore Purchases",
        premiumUnlockedTitle = "Archmage Ascension Active",
        offlineModeTitle = "Offline Oracle Sanctum",
        offlineModeDesc = "Channel prophecies even in deep underground vaults, airplane flights, or dead zones.",
        offlineLockedWarning = "Offline Divination is an exclusive Premium privilege. Connect to network or upgrade to continue channeling.",
        offlineActiveSuccess = "Offline Cosmic Leyline active. Divination is fully available.",
        simulatedOfflineToggle = "Test Offline Gate (Simulator)",
        simulatedOfflineActive = "Offline Mode Simulated (No Internet)",
        simulatedOnlineActive = "Connected to Astral Network",
        historyEmpty = "No divination records inscribed yet in the astral chronicles.",
        historySearchHint = "Search inquiries and prophecies...",
        filterAll = "All",
        filterYesNo = "Yes / No",
        filterChoice = "Choices",
        filterFavorites = "Favorites",
        clearHistory = "Clear Chronicles",
        clearHistoryConfirm = "Erase all past records?",
        askAgain = "Consult Again",
        shopTabSkins = "Orb Skins",
        shopTabAnimations = "Auras",
        shopTabStyles = "Oracle Styles",
        equipAction = "Attune Orb",
        equippedLabel = "Attuned",
        unlockFor = "Attune for",
        needMoreStardust = "Insufficient Stardust. Divine more or meditate!",
        adInterruptionTitle = "Astral Disturbance (Celestial Sponsor)",
        adInterruptionDesc = "The veil thins as worldly merchants broadcast across realms.",
        adSkipIn = "Resume divination in %d s...",
        adDismiss = "Dismiss Vision",
        adUpgradeCTA = "Remove all ads forever for $2.00",
        languageTitle = "Cosmic Dialect (Language)",
        voiceErrorPermission = "Microphone access is required to speak your questions.",
        voiceErrorNoSpeech = "No speech detected. Please speak clearly into the device."
    )

    private val SPANISH = LocalizedStrings(
        appTitle = "Oráculo de Cristal",
        tabYesNo = "Sí o No",
        tabChoice = "Elegir",
        tabShop = "Santuario",
        tabHistory = "Crónicas",
        askQuestionHint = "Haz tu pregunta a la esfera etérea...",
        speakQuestion = "Hablar Pregunta",
        divineButton = "Consultar Cristal",
        diviningPrompt = "Comulgando con el cosmos...",
        touchToCommune = "Toca o frota el cristal para enfocar energía",
        voiceListening = "Escuchando... Pronuncia tu consulta",
        needOptionsHint = "Ingresa al menos 2 opciones para elegir",
        addOption = "Añadir Opción",
        chooseForMeButton = "Adivinar Elección",
        presetsTitle = "Plantillas Místicas",
        presetFood = "¿Qué Cenar?",
        presetWeekend = "Destino del Fin de Semana",
        presetFocus = "Enfoque del Día",
        presetYesNoQuestions = listOf(
            "¿Prosperará mi proyecto actual?",
            "¿Se aproxima un amor verdadero?",
            "¿Debería hacer esa compra hoy?",
            "¿Es momento de iniciar un nuevo ciclo?"
        ),
        alignmentLabel = "Armonía Cósmica",
        stardustLabel = "Polvo Estelar",
        dailyMeditation = "Sintonización Diaria",
        meditateBonusReceived = "+100 de Polvo Estelar absorbido!",
        premiumBannerTitle = "Asciende a Archmago Premium",
        premiumBannerSub = "Elimina anuncios, adivina sin conexión y desbloquea el skin Archmago.",
        upgradeToPremium = "Ascender por $2.00",
        premiumPerksTitle = "Privilegios de Archmago",
        perkNoAds = "Cero anuncios para siempre",
        perkOffline = "Adivinación offline ilimitada (Sin internet)",
        perkExclusiveSkin = "Skin exclusivo dorado 'Archmago Eternidad'",
        perk2xStardust = "Doble polvo estelar en cada tirada",
        perkAllStyles = "Todos los estilos de adivinación desbloqueados",
        priceTwoDollars = "$2.00 Pago Único",
        buyPremiumAction = "Comprar Acceso • $2.00",
        restorePurchases = "Restaurar Compras",
        premiumUnlockedTitle = "Ascensión de Archmago Activa",
        offlineModeTitle = "Modo Sin Conexión",
        offlineModeDesc = "Adivina incluso en aviones o sin señal.",
        offlineLockedWarning = "La adivinación offline es exclusiva para usuarios Premium. Conéctate a internet o actualiza.",
        offlineActiveSuccess = "Línea cósmica offline activa. Adivina sin límites.",
        simulatedOfflineToggle = "Probar Modo Offline (Simulador)",
        simulatedOfflineActive = "Modo Offline Simulado",
        simulatedOnlineActive = "Conectado a la Red Astral",
        historyEmpty = "No hay registros grabados en las crónicas aún.",
        historySearchHint = "Buscar consultas y profecías...",
        filterAll = "Todos",
        filterYesNo = "Sí / No",
        filterChoice = "Opciones",
        filterFavorites = "Favoritos",
        clearHistory = "Limpiar Crónicas",
        clearHistoryConfirm = "¿Borrar todos los registros?",
        askAgain = "Consultar Otra Vez",
        shopTabSkins = "Aspectos",
        shopTabAnimations = "Auras",
        shopTabStyles = "Estilos",
        equipAction = "Sintonizar",
        equippedLabel = "Sintonizado",
        unlockFor = "Desbloquear por",
        needMoreStardust = "Polvo estelar insuficiente. ¡Adivina o medita!",
        adInterruptionTitle = "Visión Astral (Patrocinador)",
        adInterruptionDesc = "Un mensaje mercantil cruza las dimensiones.",
        adSkipIn = "Continuar en %d s...",
        adDismiss = "Cerrar Visión",
        adUpgradeCTA = "Quitar anuncios por siempre por $2.00",
        languageTitle = "Dialecto Cósmico",
        voiceErrorPermission = "Se requiere permiso de micrófono para hablar.",
        voiceErrorNoSpeech = "No se detectó voz. Por favor habla claro."
    )

    private val FRENCH = LocalizedStrings(
        appTitle = "Oracle de Cristal",
        tabYesNo = "Oui / Non",
        tabChoice = "Décider",
        tabShop = "Sanctuaire",
        tabHistory = "Chroniques",
        askQuestionHint = "Posez votre question à la sphère éthérée...",
        speakQuestion = "Parler",
        divineButton = "Interroger la Boule",
        diviningPrompt = "Communion avec le cosmos...",
        touchToCommune = "Frottez ou touchez la sphère pour concentrer l'énergie",
        voiceListening = "Écoute en cours... Parlez clairement",
        needOptionsHint = "Entrez au moins 2 options",
        addOption = "Ajouter Choix",
        chooseForMeButton = "Décider Pour Moi",
        presetsTitle = "Modèles Mystiques",
        presetFood = "Que Manger ce Soir ?",
        presetWeekend = "Week-end Idéal",
        presetFocus = "Priorité du Jour",
        presetYesNoQuestions = listOf(
            "Mon projet connaîtra-t-il le succès ?",
            "L'amour frappe-t-il bientôt à ma porte ?",
            "Dois-je franchir ce cap aujourd'hui ?"
        ),
        alignmentLabel = "Harmonie Cosmique",
        stardustLabel = "Poussière Stellaire",
        dailyMeditation = "Méditation Quotidienne",
        meditateBonusReceived = "+100 Poussière Stellaire reçue !",
        premiumBannerTitle = "Accédez au Rang Archimage",
        premiumBannerSub = "Supprimez la publicité, accédez au mode hors-ligne et recevez l'orbe suprême.",
        upgradeToPremium = "Devenir Archimage pour 2,00 $",
        premiumPerksTitle = "Privilèges Archimage",
        perkNoAds = "Zéro publicité à vie",
        perkOffline = "Divination hors-ligne totale (Sans connexion)",
        perkExclusiveSkin = "Sphère exclusive dorée 'Archimage Éternité'",
        perk2xStardust = "Gain de poussière doublé",
        perkAllStyles = "Tous les styles de divination débloqués",
        priceTwoDollars = "2,00 $ Paiement Unique",
        buyPremiumAction = "Acheter Accès • 2,00 $",
        restorePurchases = "Restaurer Achats",
        premiumUnlockedTitle = "Archimage Actif",
        offlineModeTitle = "Sanctuaire Hors-Ligne",
        offlineModeDesc = "Consultez l'oracle même sans réseau ni signal.",
        offlineLockedWarning = "Le mode hors-ligne est réservé aux membres Premium. Connectez-vous ou passez à Premium.",
        offlineActiveSuccess = "Ligne astrale hors-ligne active.",
        simulatedOfflineToggle = "Tester Mode Hors-Ligne (Simulateur)",
        simulatedOfflineActive = "Mode Hors-Ligne Simulé",
        simulatedOnlineActive = "Connecté au Réseau Astral",
        historyEmpty = "Aucune prophétie inscrite dans les chroniques.",
        historySearchHint = "Rechercher...",
        filterAll = "Tous",
        filterYesNo = "Oui / Non",
        filterChoice = "Choix",
        filterFavorites = "Favoris",
        clearHistory = "Effacer Chroniques",
        clearHistoryConfirm = "Supprimer tout l'historique ?",
        askAgain = "Consulter à nouveau",
        shopTabSkins = "Apparences",
        shopTabAnimations = "Auras",
        shopTabStyles = "Styles",
        equipAction = "Associer",
        equippedLabel = "Associé",
        unlockFor = "Débloquer pour",
        needMoreStardust = "Poussière insuffisante.",
        adInterruptionTitle = "Message Astral",
        adInterruptionDesc = "Une annonce marchande traverse le voile mystique.",
        adSkipIn = "Passer dans %d s...",
        adDismiss = "Fermer",
        adUpgradeCTA = "Supprimer les pubs à vie pour 2,00 $",
        languageTitle = "Langue Cosmique",
        voiceErrorPermission = "L'accès au micro est requis.",
        voiceErrorNoSpeech = "Aucune parole détectée."
    )

    private val GERMAN = LocalizedStrings(
        appTitle = "Kristall-Orakel",
        tabYesNo = "Ja / Nein",
        tabChoice = "Entscheiden",
        tabShop = "Sanktuarium",
        tabHistory = "Chronik",
        askQuestionHint = "Stelle deine Frage an die ätherische Sphäre...",
        speakQuestion = "Frage Sprechen",
        divineButton = "In den Kristall blicken",
        diviningPrompt = "Verbindung zum Kosmos wird gewebt...",
        touchToCommune = "Berühre die Kugel, um astrale Energie zu sammeln",
        voiceListening = "Zuhören... Sprich deutlich",
        needOptionsHint = "Gib mindestens 2 Optionen ein",
        addOption = "Option Hinzufügen",
        chooseForMeButton = "Wahl Erfühlen",
        presetsTitle = "Mystische Vorlagen",
        presetFood = "Was essen wir?",
        presetWeekend = "Wochenend-Schicksal",
        presetFocus = "Tagesfokus",
        presetYesNoQuestions = listOf(
            "Wird mein Vorhaben gelingen?",
            "Wartet das Glück bald auf mich?",
            "Soll ich heute diesen Schritt wagen?"
        ),
        alignmentLabel = "Kosmische Harmonie",
        stardustLabel = "Sternenstaub",
        dailyMeditation = "Tägliche Einstimmung",
        meditateBonusReceived = "+100 Sternenstaub empfangen!",
        premiumBannerTitle = "Aufstieg zum Erzmagier",
        premiumBannerSub = "Werbefrei, unbegrenzt offline weissagen und das Erzmagier-Design freischalten.",
        upgradeToPremium = "Aufsteigen für 2,00 $",
        premiumPerksTitle = "Erzmagier-Vorteile",
        perkNoAds = "Für immer komplett werbefrei",
        perkOffline = "Offline-Weissagung überall (Kein Internet nötig)",
        perkExclusiveSkin = "Exklusives Gold-Design 'Erzmagier Ewigkeit'",
        perk2xStardust = "Doppelter Sternenstaub bei jeder Lesung",
        perkAllStyles = "Alle Orakel-Stile freigeschaltet",
        priceTwoDollars = "2,00 $ Einmalig",
        buyPremiumAction = "Zugang Kaufen • 2,00 $",
        restorePurchases = "Käufe Wiederherstellen",
        premiumUnlockedTitle = "Erzmagier-Rang Aktiv",
        offlineModeTitle = "Offline-Sanktuarium",
        offlineModeDesc = "Erhalte Weissagungen auch im Flugmodus oder Funkloch.",
        offlineLockedWarning = "Offline-Weissagung ist exklusiv für Premium-Nutzer. Bitte online gehen oder upgraden.",
        offlineActiveSuccess = "Offline-Weissagung aktiviert.",
        simulatedOfflineToggle = "Offline-Modus testen (Simulator)",
        simulatedOfflineActive = "Offline-Modus simuliert",
        simulatedOnlineActive = "Verbunden mit dem Astralnetz",
        historyEmpty = "Noch keine Orakel in der Chronik vermerkt.",
        historySearchHint = "Suchen...",
        filterAll = "Alle",
        filterYesNo = "Ja / Nein",
        filterChoice = "Auswahl",
        filterFavorites = "Favoriten",
        clearHistory = "Chronik Löschen",
        clearHistoryConfirm = "Alle Einträge löschen?",
        askAgain = "Erneut Befragen",
        shopTabSkins = "Designs",
        shopTabAnimations = "Auren",
        shopTabStyles = "Stile",
        equipAction = "Aktivieren",
        equippedLabel = "Aktiv",
        unlockFor = "Freischalten für",
        needMoreStardust = "Nicht genug Sternenstaub.",
        adInterruptionTitle = "Astrale Unterbrechung",
        adInterruptionDesc = "Ein weltlicher Bote sendet durch den Schleier.",
        adSkipIn = "Überspringen in %d s...",
        adDismiss = "Schließen",
        adUpgradeCTA = "Werbung dauerhaft entfernen für 2,00 $",
        languageTitle = "Sprache",
        voiceErrorPermission = "Mikrofon-Berechtigung erforderlich.",
        voiceErrorNoSpeech = "Keine Stimme erkannt."
    )

    private val JAPANESE = LocalizedStrings(
        appTitle = "クリスタル・オラクル",
        tabYesNo = "イエス・ノー",
        tabChoice = "選択の儀",
        tabShop = "聖域の店",
        tabHistory = "年代記",
        askQuestionHint = "水晶玉に問いを投げかけてください...",
        speakQuestion = "音声で質問",
        divineButton = "水晶を覗く",
        diviningPrompt = "宇宙の波動と交信中...",
        touchToCommune = "水晶球に触れるか撫でて霊力を集中",
        voiceListening = "霊音を聴取中... はっきりとお話しください",
        needOptionsHint = "2つ以上の選択肢を入力してください",
        addOption = "選択肢を追加",
        chooseForMeButton = "神託を下す",
        presetsTitle = "神秘のプリセット",
        presetFood = "今日の夕食は？",
        presetWeekend = "週末の運命",
        presetFocus = "今日の優先課題",
        presetYesNoQuestions = listOf(
            "現在の挑戦は実を結ぶか？",
            "素晴らしい出会いが待っているか？",
            "今日決断を下すべきか？"
        ),
        alignmentLabel = "天体同調率",
        stardustLabel = "星屑",
        dailyMeditation = "毎日の水晶瞑想",
        meditateBonusReceived = "+100 星屑を獲得しました！",
        premiumBannerTitle = "大魔導士プレミアムへ昇格",
        premiumBannerSub = "完全広告非表示、オフライン神託解放、限定ゴールドスキン入手。",
        upgradeToPremium = "$2.00 で昇格する",
        premiumPerksTitle = "大魔導士の特権",
        perkNoAds = "永久に広告なし",
        perkOffline = "完全オフライン神託（機内・圏外でも使用可能）",
        perkExclusiveSkin = "限定黄金スキン「大魔導士のエタニティ」",
        perk2xStardust = "星屑獲得量が常に2倍",
        perkAllStyles = "全5種の託宣スタイルを即時解放",
        priceTwoDollars = "$2.00 永久買い切り",
        buyPremiumAction = "アクセスを購入 • $2.00",
        restorePurchases = "購入の復元",
        premiumUnlockedTitle = "大魔導士の加護が有効です",
        offlineModeTitle = "オフライン神託",
        offlineModeDesc = "圏外や飛行機内でもいつでも水晶球に相談できます。",
        offlineLockedWarning = "オフライン神託は大魔導士（Premium）限定機能です。通信を接続するかアップグレードしてください。",
        offlineActiveSuccess = "オフライン交信が有効です。どこでも神託を受けられます。",
        simulatedOfflineToggle = "オフライン挙動をテスト（シミュレータ）",
        simulatedOfflineActive = "オフライン状態（圏外シミュレーション中）",
        simulatedOnlineActive = "星界ネットワーク接続中",
        historyEmpty = "まだ年代記に神託の記録がありません。",
        historySearchHint = "問いや予言を検索...",
        filterAll = "すべて",
        filterYesNo = "YES/NO",
        filterChoice = "選択肢",
        filterFavorites = "お気に入り",
        clearHistory = "年代記を消去",
        clearHistoryConfirm = "全ての履歴を消去しますか？",
        askAgain = "再相談する",
        shopTabSkins = "水晶スキン",
        shopTabAnimations = "オーラ",
        shopTabStyles = "予言スタイル",
        equipAction = "装着",
        equippedLabel = "装着中",
        unlockFor = "解放：",
        needMoreStardust = "星屑が足りません。神託を重ねるか瞑想しましょう！",
        adInterruptionTitle = "星界の商人の幻影",
        adInterruptionDesc = "霊界を通り抜ける商人の伝言です。",
        adSkipIn = "%d 秒後にスキップ...",
        adDismiss = "閉じる",
        adUpgradeCTA = "$2.00で永久に広告を消去",
        languageTitle = "言語設定",
        voiceErrorPermission = "マイクへのアクセス権限が必要です。",
        voiceErrorNoSpeech = "音声が検出されませんでした。"
    )

    private val CHINESE = LocalizedStrings(
        appTitle = "水晶神谕",
        tabYesNo = "是与否",
        tabChoice = "抉择",
        tabShop = "圣殿",
        tabHistory = "编年史",
        askQuestionHint = "向神秘水晶球提出你的问题...",
        speakQuestion = "语音提问",
        divineButton = "凝视水晶",
        diviningPrompt = "正在与群星感应交融...",
        touchToCommune = "触摸或抚摸水晶球以汇聚星辉能量",
        voiceListening = "聆听中... 请清晰说出你的问题",
        needOptionsHint = "请输入至少两个选项供神谕裁决",
        addOption = "添加选项",
        chooseForMeButton = "神谕抉择",
        presetsTitle = "神秘预设",
        presetFood = "今天吃什么？",
        presetWeekend = "周末去向",
        presetFocus = "今日焦点",
        presetYesNoQuestions = listOf(
            "我当下的努力会取得辉煌成果吗？",
            "真诚的良缘即将来临吗？",
            "今天是否适合迈出大胆的一步？"
        ),
        alignmentLabel = "星宿共鸣度",
        stardustLabel = "星尘",
        dailyMeditation = "每日水晶冥想",
        meditateBonusReceived = "+100 星尘已注入灵体！",
        premiumBannerTitle = "飞升大魔导师特权",
        premiumBannerSub = "永久免除广告，解锁离线全能神谕，专属纯金永恒之球。",
        upgradeToPremium = "$2.00 永久飞升",
        premiumPerksTitle = "大魔导师专属特权",
        perkNoAds = "永久完全无广告",
        perkOffline = "无网离线神谕（飞行模式/地堡随时随地使用）",
        perkExclusiveSkin = "专属纯金幻光球体「永恒大法师」",
        perk2xStardust = "每次占卜星尘获取翻倍",
        perkAllStyles = "全部占卜性格风格瞬间解锁",
        priceTwoDollars = "$2.00 一次性终身买断",
        buyPremiumAction = "立即购买 • $2.00",
        restorePurchases = "恢复购买",
        premiumUnlockedTitle = "大魔导师特权已激活",
        offlineModeTitle = "离线星光圣殿",
        offlineModeDesc = "即便身处深山密室或飞行模式，群星智慧依然与你同在。",
        offlineLockedWarning = "离线占卜为高级特权。请连接网络或升级大魔导师以继续畅享。",
        offlineActiveSuccess = "离线星光共鸣已就绪，随时开启占卜。",
        simulatedOfflineToggle = "测试离线拦截（模拟器）",
        simulatedOfflineActive = "已模拟断网状态（无网络）",
        simulatedOnlineActive = "星界连接正常",
        historyEmpty = "编年史中暂无记录。",
        historySearchHint = "搜索占卜历史与谶语...",
        filterAll = "全部",
        filterYesNo = "是/否",
        filterChoice = "多选抉择",
        filterFavorites = "星标珍藏",
        clearHistory = "清空记录",
        clearHistoryConfirm = "确认清除所有占卜史册？",
        askAgain = "再次请教",
        shopTabSkins = "水晶外观",
        shopTabAnimations = "灵光特效",
        shopTabStyles = "神谕文风",
        equipAction = "共鸣佩戴",
        equippedLabel = "共鸣中",
        unlockFor = "消耗解锁：",
        needMoreStardust = "星尘不足。请多占卜或进行每日冥想！",
        adInterruptionTitle = "星界商盟投影",
        adInterruptionDesc = "世俗商贩的幻象投射过结界。",
        adSkipIn = "%d 秒后可跳过...",
        adDismiss = "关闭幻象",
        adUpgradeCTA = "花费 $2.00 永久抹除一切凡尘广告",
        languageTitle = "语言设定",
        voiceErrorPermission = "需要麦克风权限以聆听您的声音。",
        voiceErrorNoSpeech = "未识别到语音，请对准麦克风清晰诉说。"
    )

    private val PORTUGUESE = LocalizedStrings(
        appTitle = "Oráculo de Cristal",
        tabYesNo = "Sim / Não",
        tabChoice = "Escolher",
        tabShop = "Santuário",
        tabHistory = "Crônicas",
        askQuestionHint = "Faça sua pergunta à esfera etérea...",
        speakQuestion = "Falar Pergunta",
        divineButton = "Consultar Cristal",
        diviningPrompt = "Em comunhão com o cosmo...",
        touchToCommune = "Toque ou esfregue a esfera para focar energia",
        voiceListening = "Ouvindo... Fale com clareza",
        needOptionsHint = "Insira pelo menos 2 opções",
        addOption = "Adicionar Opção",
        chooseForMeButton = "Adivinhar Escolha",
        presetsTitle = "Modelos Místicos",
        presetFood = "O que jantar?",
        presetWeekend = "Destino do Fim de Semana",
        presetFocus = "Foco do Dia",
        presetYesNoQuestions = listOf(
            "Meu projeto atual prosperará?",
            "Um novo amor se aproxima?",
            "Devo arriscar hoje?"
        ),
        alignmentLabel = "Harmonia Cósmica",
        stardustLabel = "Poeira Estelar",
        dailyMeditation = "Sintonia Diária",
        meditateBonusReceived = "+100 de Poeira Estelar absorvida!",
        premiumBannerTitle = "Torne-se Arquimago Premium",
        premiumBannerSub = "Sem anúncios, consulte offline e ganhe a esfera dourada eterna.",
        upgradeToPremium = "Ascender por $2.00",
        premiumPerksTitle = "Privilégios de Arquimago",
        perkNoAds = "Zero anúncios para sempre",
        perkOffline = "Adivinhação offline completa (Sem internet)",
        perkExclusiveSkin = "Visual exclusivo dourado 'Arquimago Eternidade'",
        perk2xStardust = "Dobro de poeira estelar em cada leitura",
        perkAllStyles = "Todos os estilos de adivinhação desbloqueados",
        priceTwoDollars = "$2.00 Pagamento Único",
        buyPremiumAction = "Comprar Acesso • $2.00",
        restorePurchases = "Restaurar Compras",
        premiumUnlockedTitle = "Grau de Arquimago Ativo",
        offlineModeTitle = "Santuário Offline",
        offlineModeDesc = "Consulte o oráculo no avião ou sem sinal de rede.",
        offlineLockedWarning = "O modo offline é exclusivo para membros Premium. Conecte-se ou atualize para continuar.",
        offlineActiveSuccess = "Linha cósmica offline ativa.",
        simulatedOfflineToggle = "Testar Modo Offline (Simulador)",
        simulatedOfflineActive = "Modo Offline Simulado",
        simulatedOnlineActive = "Conectado à Rede Astral",
        historyEmpty = "Nenhum oráculo registrado nas crônicas ainda.",
        historySearchHint = "Buscar registros...",
        filterAll = "Todos",
        filterYesNo = "Sim / Não",
        filterChoice = "Escolhas",
        filterFavorites = "Favoritos",
        clearHistory = "Limpar Crônicas",
        clearHistoryConfirm = "Apagar todo o histórico?",
        askAgain = "Consultar Novamente",
        shopTabSkins = "Esferas",
        shopTabAnimations = "Auras",
        shopTabStyles = "Estilos",
        equipAction = "Sintonizar",
        equippedLabel = "Sintonizado",
        unlockFor = "Desbloquear por",
        needMoreStardust = "Poeira estelar insuficiente.",
        adInterruptionTitle = "Visão Astral de Patrocinador",
        adInterruptionDesc = "Uma mensagem cruza o véu.",
        adSkipIn = "Pular em %d s...",
        adDismiss = "Fechar",
        adUpgradeCTA = "Remover anúncios para sempre por $2.00",
        languageTitle = "Idioma",
        voiceErrorPermission = "Acesso ao microfone necessário.",
        voiceErrorNoSpeech = "Nenhuma voz detectada."
    )

    private val ITALIAN = LocalizedStrings(
        appTitle = "Oracolo di Cristallo",
        tabYesNo = "Sì / No",
        tabChoice = "Scegliere",
        tabShop = "Santuario",
        tabHistory = "Cronache",
        askQuestionHint = "Poni la tua domanda alla sfera eterea...",
        speakQuestion = "Parla al Cristallo",
        divineButton = "Interroga la Sfera",
        diviningPrompt = "In comunione con le stelle...",
        touchToCommune = "Tocca o sfrega la sfera per concentrare il flusso",
        voiceListening = "In ascolto... Parla chiaramente",
        needOptionsHint = "Inserisci almeno 2 opzioni",
        addOption = "Aggiungi Scelta",
        chooseForMeButton = "Rivela la Scelta",
        presetsTitle = "Modelli Mistici",
        presetFood = "Cosa Mangiare?",
        presetWeekend = "Destino del Weekend",
        presetFocus = "Obiettivo del Giorno",
        presetYesNoQuestions = listOf(
            "Il mio progetto avrà successo?",
            "L'amore vero sta arrivando?",
            "Dovrei osare oggi?"
        ),
        alignmentLabel = "Armonia Cosmica",
        stardustLabel = "Polvere di Stelle",
        dailyMeditation = "Sintonizzazione Quotidiana",
        meditateBonusReceived = "+100 Polvere di Stelle raccolta!",
        premiumBannerTitle = "Diventa Arcimago Premium",
        premiumBannerSub = "Nessuna pubblicità, divinazione offline e la sfera dorata suprema.",
        upgradeToPremium = "Accedi per $2.00",
        premiumPerksTitle = "Privilegi dell'Arcimago",
        perkNoAds = "Nessun annuncio per sempre",
        perkOffline = "Divinazione offline ovunque (Senza connessione)",
        perkExclusiveSkin = "Sfera dorata esclusiva 'Arcimago Eternità'",
        perk2xStardust = "Polvere di stelle raddoppiata",
        perkAllStyles = "Tutti gli stili di divinazione sbloccati",
        priceTwoDollars = "$2.00 Pagamento Unico",
        buyPremiumAction = "Acquista Accesso • $2.00",
        restorePurchases = "Ripristina Acquisti",
        premiumUnlockedTitle = "Grado di Arcimago Attivo",
        offlineModeTitle = "Santuario Offline",
        offlineModeDesc = "Interroga l'oracolo anche in aereo o senza campo.",
        offlineLockedWarning = "La modalità offline è esclusiva per gli utenti Premium. Connettiti o passa a Premium.",
        offlineActiveSuccess = "Linea astrale offline attiva.",
        simulatedOfflineToggle = "Testa Modalità Offline (Simulatore)",
        simulatedOfflineActive = "Modalità Offline Simulata",
        simulatedOnlineActive = "Connesso alla Rete Astrale",
        historyEmpty = "Nessuna profezia ancora incisa nelle cronache.",
        historySearchHint = "Cerca nelle cronache...",
        filterAll = "Tutti",
        filterYesNo = "Sì / No",
        filterChoice = "Scelte",
        filterFavorites = "Preferiti",
        clearHistory = "Cancella Cronache",
        clearHistoryConfirm = "Eliminare tutta la cronologia?",
        askAgain = "Consulta Ancora",
        shopTabSkins = "Sfere",
        shopTabAnimations = "Aure",
        shopTabStyles = "Stili",
        equipAction = "Sintonizza",
        equippedLabel = "Sintonizzato",
        unlockFor = "Sblocca per",
        needMoreStardust = "Polvere di stelle insufficiente.",
        adInterruptionTitle = "Messaggio Astrale",
        adInterruptionDesc = "Una visione commerciale attraversa il velo.",
        adSkipIn = "Salta tra %d s...",
        adDismiss = "Chiudi",
        adUpgradeCTA = "Rimuovi la pubblicità a vita per $2.00",
        languageTitle = "Lingua",
        voiceErrorPermission = "Autorizzazione microfono richiesta.",
        voiceErrorNoSpeech = "Nessuna voce rilevata."
    )
}
